baseurl = "http://sensu-docs-site.herokuapp.com"
languageCode = "en-us"
title = "Sensu Docs"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyURLs = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = ""

[params]
	# General information
	author = "Sensu, Inc"
	description = "Monitor servers, services, application health, and business KPIs. Collect and analyze custom metrics. Get notified about failures before your users do. Give your business the competitive advantage it deserves."
	copyright = ""
    disableKinds = ["taxonomy","taxonomyTerm"]

	# Repository
	provider = "GitHub"
	repo_url = "https://github.com/sensu/sensu-docs"

	version = "1.00"
	logo = "images/logo-flat-black.png"
	favicon = "images/logo-flat-black.png"

	permalink = "#"

	# Custom assets
	custom_css = []
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "green"
     	accent  = "green"

    [params.font]
    	text = "Ubuntu"
    	code = "Ubuntu Mono"

    [params.products.sensu_core]
        identifier = "sensu-core"
        name = "Sensu Core"
        description = "Sensu helps monitoring and does some cool things. It's neato!"
        weight = 1
        versions = [0.29, 1.00]

    [params.products.sensu_enterprise]
        identifier = "sensu-enterprise"
        name = "Sensu Enterprise"
        description = "Sensu for paying customers. You get some additional things."
        weight = 2
        versions = [0.5, 1.00]

    [params.products.sensu_enterprise_dashboard]
        identifier = "sensu-enterprise-dashboard"
        name = "Sensu Enterprise Dashboard"
        description = "The dashboard is quite fancy and super helpful."
        weight = 3
        versions = [0.65, 1.00]

    [params.products.uchiwa]
        identifier = "uchiwa"
        name = "Uchiwa"
        description = "Uchiwa is a dashboard that integrates with Sensu. It's basically a must."
        weight = 4
        versions = [1.00, 1.40]

    [params.products.plugins]
        identifier = "plugins"
        name = "Plugins"
        description = "Plugins to add capabilities to Sensu."
        weight = 5
        versions = [0.30, 1.00]

    [params.products.extensions]
        identifier = "extensions"
        name = "Extensions"
        description = "Extensions to extend Sensu."
        weight = 6
        versions = [0.12, 1.00]

[social]
	twitter = "sensu"
	github  = "sensu"
	email   = ""

[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true
