baseurl = "https://sensu-docs-site.herokuapp.com/"
languageCode = "en-us"
title = "Sensu Docs"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyURLs = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = ""

[params]
	# General information
	author = "Sensu, Inc"
	description = "Monitor servers, services, application health, and business KPIs. Collect and analyze custom metrics. Get notified about failures before your users do. Give your business the competitive advantage it deserves."
	copyright = ""

	# Repository
	provider = "GitHub"
	repo_url = "https://github.com/sensu/sensu-docs"

	version = "1.0.0"
	logo = "images/logo-flat-black.png"
	favicon = "images/logo-flat-black.png"

	permalink = "#"

	# Custom assets
	custom_css = []
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "green"
     	accent  = "green"

    [params.font]
    	text = "Ubuntu"
    	code = "Ubuntu Mono"

[social]
	twitter = "sensu"
	github  = "sensu"
	email   = ""

[[menu.main]]
    name = "Sensu Docs"
    url = "/"
    weight = 0

[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true
